// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQaC8bXsb6UgrITmko78nhmNsrVgP3zI',
    appId: '1:513391357564:web:fe5475be3dd0f3f187e3f9',
    messagingSenderId: '513391357564',
    projectId: 'bep-tro-ly',
    authDomain: 'bep-tro-ly.firebaseapp.com',
    storageBucket: 'bep-tro-ly.firebasestorage.app',
    measurementId: 'G-DR203W78TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHirYpIRICvKgBru_sE4ogOZLiHYQ4PQ',
    appId: '1:513391357564:android:988541e177cc199c87e3f9',
    messagingSenderId: '513391357564',
    projectId: 'bep-tro-ly',
    storageBucket: 'bep-tro-ly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSARJ-OAZmKEdTXcjB7IiwdKJuiTfclhQ',
    appId: '1:513391357564:ios:7aed0fbfa9cc1e1c87e3f9',
    messagingSenderId: '513391357564',
    projectId: 'bep-tro-ly',
    storageBucket: 'bep-tro-ly.firebasestorage.app',
    iosClientId: '513391357564-bba32qqda79266caqvas90cf8b8qa8d5.apps.googleusercontent.com',
    iosBundleId: 'btl.tlu.beptroly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSARJ-OAZmKEdTXcjB7IiwdKJuiTfclhQ',
    appId: '1:513391357564:ios:7aed0fbfa9cc1e1c87e3f9',
    messagingSenderId: '513391357564',
    projectId: 'bep-tro-ly',
    storageBucket: 'bep-tro-ly.firebasestorage.app',
    iosClientId: '513391357564-bba32qqda79266caqvas90cf8b8qa8d5.apps.googleusercontent.com',
    iosBundleId: 'btl.tlu.beptroly',
  );

}