// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIqE3S_iAyrUrK4pjqHMrjZqlTNCNrRE',
    appId: '1:928261089448:android:a48ac1a0326f41f7313a9d',
    messagingSenderId: '928261089448',
    projectId: 'appmaterials2025',
    storageBucket: 'appmaterials2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-njDgIfDo7bStTkobnJLZVi22y0ZUGIo',
    appId: '1:928261089448:ios:b84e927bb0ddf57c313a9d',
    messagingSenderId: '928261089448',
    projectId: 'appmaterials2025',
    storageBucket: 'appmaterials2025.firebasestorage.app',
    iosBundleId: 'btl.tlu.beptroly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-njDgIfDo7bStTkobnJLZVi22y0ZUGIo',
    appId: '1:928261089448:ios:b84e927bb0ddf57c313a9d',
    messagingSenderId: '928261089448',
    projectId: 'appmaterials2025',
    storageBucket: 'appmaterials2025.firebasestorage.app',
    iosBundleId: 'btl.tlu.beptroly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DpZM_pcV6M2KHrg8aMxPNgtKJvJsf1c',
    appId: '1:928261089448:web:676d45d9d9af2544313a9d',
    messagingSenderId: '928261089448',
    projectId: 'appmaterials2025',
    authDomain: 'appmaterials2025.firebaseapp.com',
    storageBucket: 'appmaterials2025.firebasestorage.app',
    measurementId: 'G-MRDRQV2YW5',
  );

}